name: Deploy

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vinyl-api
          build-args: |
            PORT=${{ env.PORT }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull image and run container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          key: ${{ secrets.GCP_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/vinyl-api
          docker run -d -p 80:80 --name vinyl -e JWT_SECRET=${{ secrets.JWT_SECRET }} ${{ secrets.DOCKERHUB_USERNAME }}/vinyl-api
