name: Deploy

on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  CONTAINER_NAME: vinyl
  IMAGE_NAME: vinyl-api

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME
          build-args: |
            PORT=${{ env.PORT }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Pull image and run container
        uses: appleboy/ssh-action@v0.1.10
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          key: ${{ secrets.GCP_KEY }}
          envs: DOCKERHUB_USERNAME,JWT_SECRET,CONTAINER_NAME,IMAGE_NAME
          script: |
            docker container rm -f $CONTAINER_NAME
            docker image rm -f $DOCKERHUB_USERNAME/$IMAGE_NAME
            docker run -d -p 80:80 --name $CONTAINER_NAME -e JWT_SECRET=$JWT_SECRET $DOCKERHUB_USERNAME/$IMAGE_NAME
